### ISSUE TITLE
code-review comments

### ISSUE THREAD

**Issue by balmas** [alpheios-project/client-adapters#1]
Comments as of commit 11952fcbeebd78ad80cab6aac6c04b9890f9c1f8:

I think the code is going in the right direction. A few initial observations:

* Generally, I like the new API interface of 
```
ClientAdapters.<AdapterClass>({
        type: '<apiMethod>',
        languageID: <languageID>
        paramX: <paramValue>
      })
```

One way to make this even a bit nicer might be to have the parameters specified in a 2nd level, e.g.
```
ClientAdapters.<AdapterClass>({
        method: '<apiMethod>',
        params: { 
          languageID: <languageID>
          paramX: <paramValue>
        }
      })
```

* the alpheiostb and tufts adapters are both in the category of morphological adapters. I'm leaning towards suggesting that we keep this layer of abstraction in the interface. In the case of the morphology adapters, they do implement a common apiMethod, getHomonym, and just the parameters passed differ (wordref vs word). I can envision having other morphological adapters in the future (for example, we may want to extract morphology embedded in data attributes in the page).  We could also eventually have other lexicon adapters, for example, there is a service at http://logeion.uchicago.edu/ which exposes an API which I would like to use to access their dictionaries.  So, maybe a structure like the following would be good: `ClientAdapters.<category>.<provider>`

e.g.

```
ClientAdapters.morphology.alpheiosTreebank
ClientAdapters.morphology.tufts
ClientAdapters.lexicon.alpheios
ClientAdapters.lemmatranslation.alpheios
```

* keeping the category layer could also facilitate the structure of an aggregated configuration file, which I think might be a good improvement over keeping individual config files with each adapter library. 

```
{
  'lemmatranslation': {
  
     'alpheios': {
         ...
      } 
   },
   'morphology': {
     'alpheiosTreebank': {
        ...
     }
   }
}
```

* I'm not sure about moving the feature array from the tufts morphology adapter into the config file though. To me, this is very distinct information that is tied to the functioning of the adapter itself, and not really a configurable property.

**Comment by irina060981** [comment]
Thank you, Bridget, for your feedback!

I agree with you about creating configuration more structured and divided to levels and move it to some configuration file. 

About configurations - I have moved it to a separate class only for having the same way of uploading json files and having constants somewhere saved (separate from adapter to have a cleaner code).
Also I in some adapter I created TransformAdapter and in other I didn't  - because I was trying different variants what would be the best to work with.
I am not sure what configuartion here will be the best. Thank you for opinion - I will think over again.

I see my next steps (after Safari / styles issues) here:

1) Rearrange structure of ClientAdapter API, create some configuration's files/ structures
2) Decide should the library have ConfigData class, TransformAdapter class
3) Make reorganization to remove duplicate code
4) Optimize parsing data (transforms methods)

**Comment by balmas** [comment]
sounds good. 

I will take another look at the TransformAdapter structure and see if I can provide any additional thoughts on that. @kirlat you are also welcome to weigh in!

**Comment by kirlat** [comment]
I like the new clean interface a lot! I also think a combined config file would be easier to manage.

I'm wondering how would we handle errors if they occur during data retrieval. Would they be streamed via rejected promises?

**Comment by irina060981** [comment]
Thank you, @kirlat !
I have forgotten to put it to the plan:

1) Rearrange structure of ClientAdapter API, create some configuration's files/ structures
2) Decide should the library have ConfigData class, TransformAdapter class
3) Add handling with errors
4) Make reorganization to remove duplicate code
5) Optimize parsing data (transforms methods)

If to be honest - I don't like Promise catch approach because it makes finding error a very difficult task.
But if I won't be able to suggest something better - I would add it.

**Comment by balmas** [comment]
@irina060981 when you come back to the error handling design, please make note of https://github.com/alpheios-project/components/issues/277 Thanks!

**Comment by irina060981** [comment]
All items are done.
Updated components repo, webextension repo and embedded-lib repo to use with client-adapters.
